# Generated by Django 4.1.3 on 2024-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('tc_no', models.CharField(max_length=11)),
                ('std_no', models.CharField(max_length=6)),
                ('grade', models.CharField(max_length=2)),
                ('absentee', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
