# Generated by Django 4.1.3 on 2024-04-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
