# Generated by Django 4.1.3 on 2024-04-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0002_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('authority', models.CharField(max_length=15)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_code', models.CharField(max_length=6)),
                ('lesson_text', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='WeeklyShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eokul_app.lesson')),
                ('students', models.ManyToManyField(to='eokul_app.student')),
            ],
            options={
                'db_table': 'weekly_shedule',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1_grade', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('exam2_grade', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eokul_app.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='eokul_app.student')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
