# Generated by Django 5.0.4 on 2024-04-24 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0003_administrator_lesson_weeklyshedule_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
