# Generated by Django 5.0.4 on 2024-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0004_alter_student_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
