# Generated by Django 5.0.4 on 2024-04-24 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0005_alter_student_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
