# Generated by Django 5.0.4 on 2024-04-24 10:26

import eokul_app.models.student
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0007_alter_grade_created_time_alter_grade_deleted_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=2, validators=[eokul_app.models.student.validate_grade]),
        ),
    ]
