# Generated by Django 5.0.4 on 2024-04-24 10:38

import eokul_app.models.student
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0008_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_no',
            field=models.CharField(max_length=6, validators=[eokul_app.models.student.validate_std_no]),
        ),
        migrations.AlterField(
            model_name='student',
            name='tc_no',
            field=models.CharField(max_length=11, validators=[eokul_app.models.student.validate_tc]),
        ),
    ]
