# Generated by Django 5.0.4 on 2024-04-24 10:39

import eokul_app.models.student
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0009_alter_student_std_no_alter_student_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='absentee',
            field=models.IntegerField(default=0, validators=[eokul_app.models.student.validate_absentee]),
        ),
    ]
