# Generated by Django 5.0.4 on 2024-04-25 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0010_alter_student_absentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='authority',
            field=models.CharField(choices=[('Mudur', 'Müdür'), ('Ogretmen', 'Öğretmen')], max_length=15),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam1_grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam2_grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Lesson code must start with a letter.', regex='^[a-zA-Z].*$')]),
        ),
    ]
