# Generated by Django 5.0.4 on 2024-04-25 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0011_alter_administrator_authority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eokul_app.lesson')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eokul_app.student')),
            ],
            options={
                'db_table': 'students_lesson',
            },
        ),
    ]
