# Generated by Django 5.0.4 on 2024-04-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eokul_app', '0012_studentslesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentslesson',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='studentslesson',
            old_name='student_id',
            new_name='student',
        ),
    ]
